# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-01 10:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='title',
            field=models.CharField(default=datetime.datetime(2018, 6, 1, 10, 3, 14, 637525), max_length=120),
            preserve_default=False,
        ),
    ]
