# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-06 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
