# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-01 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='title',
        ),
    ]
